-- Run as a a user with DV_ACCTMGR role in the PDB.

connect dbv_acctmgr_pdb1/ChangeMe234@pdb1

SET DEFINE OFF

PROMPT Creating demo users...

BEGIN
    EXECUTE IMMEDIATE 'CREATE USER app_owner IDENTIFIED BY "ChangeMe234" DEFAULT TABLESPACE users TEMPORARY TABLESPACE temp QUOTA UNLIMITED ON users';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -01920 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE USER app_user IDENTIFIED BY "ChangeMe234"';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -01920 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE USER powerful_user IDENTIFIED BY "ChangeMe234"';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -01920 THEN RAISE; END IF;
END;
/

GRANT CREATE SESSION TO app_owner;
GRANT CREATE SESSION TO app_user;
GRANT CREATE SESSION TO powerful_user;

connect sys@pdb1 as sysdba

GRANT CREATE TABLE to app_owner;
