-- Run as a privileged administrator in the demo PDB.

SET DEFINE OFF

PROMPT Creating demo users...

BEGIN
    EXECUTE IMMEDIATE 'CREATE USER app_owner IDENTIFIED BY "Oracle123"';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -01920 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE USER app_user IDENTIFIED BY "Oracle123"';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -01920 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE USER powerful_user IDENTIFIED BY "Oracle123"';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -01920 THEN RAISE; END IF;
END;
/

GRANT CREATE SESSION, CREATE TABLE TO app_owner;
GRANT CREATE SESSION TO app_user;
GRANT CREATE SESSION TO powerful_user;
